# Generated by Django 3.0 on 2023-01-30 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(choices=[('Adrar', ''), ('Chlef', ''), ('Laghouat', ''), ('Oum El Bouaghi', ''), ('Batna', ''), ('Béjaia', ''), ('Biskra', ''), ('Béchar', ''), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saida', 'Saida'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ('Msila', 'Msila'), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdès', 'Boumerdès'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naama', 'Naama'), ('Ain Témouchent', 'Ain Témouchent'), ('Ghardaia', 'Ghardaia'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('Bordj Badji Mokhtar', 'Bordj Badji Mokhtar'), ('Ouled Djellal', 'Ouled Djellal'), ('Béni Abbès', 'Béni Abbès'), ('In Salah', 'In Salah'), ('In Guezzam', 'In Guezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ('El Mghair', 'El Mghair'), ('El Meniaa', 'El Meniaa')], max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('adresse', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('Primaire', 'Primaire'), ('CEM', 'CEM'), ('Lycee', 'Lycee')], max_length=10)),
                ('theme', models.CharField(choices=[('Amazigh', 'Amazigh'), ('Anglais', 'Anglais'), ('Arabe', 'Arabe'), ('Education civile', 'Education civile'), ('Comptabilité et gestion financière', 'Comptabilité et gestion financière'), ('Economie et management', 'Economie et management'), ('Espagnol', 'Espagnol'), ('Français', 'Français'), ('Allemand', 'Allemand'), ('Education islamique', 'Education islamique'), ('Italien', 'Italien'), ('Mathématiques', 'Mathématiques'), ('Physique', 'Physique'), ('Sciences naturelles', 'Sciences naturelles'), ('Technologie', 'Technologie'), ('Jurisprudence', 'Jurisprudence')], max_length=50)),
                ('modalite', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('lienGoogleMap', models.URLField()),
                ('Annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAnnonces.Lieu')),
            ],
        ),
    ]
